# Generated by Django 5.0.3 on 2024-03-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_comment_id_alter_restaurant_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['created_at']},
        ),
    ]
