# Generated by Django 5.0.3 on 2024-03-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={},
        ),
    ]
